-- Type definitions for chalk.nvim colorscheme
-- Provides better development experience and documentation
-- This module defines all types used throughout chalk.nvim

local M = {}

---@class chalk.Highlight: vim.api.keyset.highlight
---@field style? vim.api.keyset.highlight Additional style options

---@alias chalk.Highlights table<string,chalk.Highlight|string>
---@alias chalk.HighlightsFn fun(colors: chalk.ColorScheme, opts: chalk.Config): chalk.Highlights

---@class chalk.Config
---@field variant string Theme variant: "default", "light", "oled"
---@field light_variant string Light theme variant when background=light
---@field transparent boolean Enable transparent backgrounds
---@field terminal_colors boolean Set terminal colors
---@field styles table<string, table> Style configurations for syntax elements
---@field dim_inactive boolean Dim inactive windows
---@field cache boolean Enable caching for performance
---@field on_colors fun(colors: chalk.ColorScheme) Callback to modify colors
---@field on_highlights fun(highlights: chalk.Highlights, colors: chalk.ColorScheme) Callback to modify highlights
---@field plugins table<string, boolean|{enabled:boolean}> Plugin integration settings
---@field integrations? table<string, boolean|{enabled:boolean}> Legacy plugin integration settings (deprecated)
---@field custom_highlights? function|table Legacy custom highlights (deprecated)

---@class chalk.ColorScheme: chalk.Palette Base color palette with semantic colors
---@field bg_1 string Lightest background color
---@field bg_2 string Light background color
---@field bg_3 string Main background color
---@field bg_4 string Dark background color
---@field bg_5 string Darkest background color
---@field fg string Main foreground color
---@field fg_dark string Dark foreground color
---@field fg_darker string Darker foreground color
---@field fg_light string Light foreground color
---@field none string Transparent color constant
---@field primary string Primary accent color
---@field secondary string Secondary accent color
---@field accent string Accent color
---@field error string Error color
---@field warning string Warning color
---@field info string Info color
---@field hint string Hint color
---@field success string Success color
---@field purple string Purple color
---@field blue string Blue color
---@field red string Red color
---@field green string Green color
---@field mahogany string Mahogany color
---@field orange string Orange color
---@field yellow string Yellow color
---@field cyan string Cyan color
---@field comment string Comment color
---@field amber string Warm amber color
---@field bronze string Metallic bronze color
---@field burgundy string Deep wine red color
---@field burnt_orange string Muted orange color
---@field copper string Sharp deep orange-brown color
---@field crimson string Sharp deep red color
---@field dusty_rose string Muted rose color
---@field emerald string Sharp deep green color
---@field forest string Sharp deep forest green color
---@field honey string Sharp deep golden brown color
---@field indian_red string Muted red-brown color
---@field indigo string Sharp deep purple-blue color
---@field mauve string Dusty purple color
---@field moss string Deep muted green color
---@field navy string Sharp deep navy blue color
---@field olive string Muted yellow-green color
---@field pewter string Gray with warmth color
---@field pine string Sharp deep pine green color
---@field plum string Deep muted purple color
---@field rust string Oxidized orange-red color
---@field sage_green string Muted green color
---@field slate string Sharp deep slate color
---@field slate_blue string Muted blue-gray color
---@field soft_blue string Soft periwinkle blue color
---@field steel string Cool gray color
---@field stone string Natural gray color
---@field teal_gray string Muted teal color
---@field terracotta string Earthy red-brown color
---@field violet string Sharp deep purple color
---@field light_gray string Light gray color
---@field selection string Selection background
---@field search string Search highlight color
---@field match string Matching bracket color
---@field cursor string Cursor color
---@field cursor_line string Cursor line background
---@field line_number string Line number color
---@field line_number_current string Current line number color
---@field menu_bg string Menu background color
---@field menu_sel string Menu selection color
---@field menu_border string Menu border color
---@field float_bg string Float window background
---@field float_border string Float window border
---@field diagnostic_error string Diagnostic error color
---@field diagnostic_warning string Diagnostic warning color
---@field diagnostic_info string Diagnostic info color
---@field diagnostic_hint string Diagnostic hint color
---@field git_add string Git addition color
---@field git_change string Git change color
---@field git_delete string Git deletion color
---@field git_text string Git text color
---@field diff_add string Diff addition color
---@field diff_delete string Diff deletion color
---@field diff_change string Diff change color
---@field diff_text string Diff text color

---@class chalk.Palette Raw color palette with organized 5-shade families
-- === MAIN COLOR FAMILIES ===
---@field amber_1 string Lightest amber shade
---@field amber_2 string Light amber shade
---@field amber_3 string Base amber shade
---@field amber_4 string Dark amber shade
---@field amber_5 string Darkest amber shade
---@field emerald_1 string Lightest emerald shade
---@field emerald_2 string Light emerald shade
---@field emerald_3 string Base emerald shade
---@field emerald_4 string Dark emerald shade
---@field emerald_5 string Darkest emerald shade
---@field azure_1 string Lightest azure shade
---@field azure_2 string Light azure shade
---@field azure_3 string Base azure shade
---@field azure_4 string Dark azure shade
---@field azure_5 string Darkest azure shade
---@field ruby_1 string Lightest ruby shade
---@field ruby_2 string Light ruby shade
---@field ruby_3 string Base ruby shade
---@field ruby_4 string Dark ruby shade
---@field ruby_5 string Darkest ruby shade
---@field amethyst_1 string Lightest amethyst shade
---@field amethyst_2 string Light amethyst shade
---@field amethyst_3 string Base amethyst shade
---@field amethyst_4 string Dark amethyst shade
---@field amethyst_5 string Darkest amethyst shade
---@field slate_1 string Lightest slate shade
---@field slate_2 string Light slate shade
---@field slate_3 string Base slate shade
---@field slate_4 string Dark slate shade
---@field slate_5 string Darkest slate shade
---@field coral_1 string Lightest coral shade
---@field coral_2 string Light coral shade
---@field coral_3 string Base coral shade
---@field coral_4 string Dark coral shade
---@field coral_5 string Darkest coral shade
---@field teal_1 string Lightest teal shade
---@field teal_2 string Light teal shade
---@field teal_3 string Base teal shade
---@field teal_4 string Dark teal shade
---@field teal_5 string Darkest teal shade
---@field rose_1 string Lightest rose shade
---@field rose_2 string Light rose shade
---@field rose_3 string Base rose shade
---@field rose_4 string Dark rose shade
---@field rose_5 string Darkest rose shade
---@field sage_1 string Lightest sage shade
---@field sage_2 string Light sage shade
---@field sage_3 string Base sage shade
---@field sage_4 string Dark sage shade
---@field sage_5 string Darkest sage shade
-- === EXTENDED FAMILIES ===
---@field bronze_1 string Lightest bronze shade
---@field bronze_2 string Light bronze shade
---@field bronze_3 string Base bronze shade
---@field bronze_4 string Dark bronze shade
---@field bronze_5 string Darkest bronze shade
---@field copper_1 string Lightest copper shade
---@field copper_2 string Light copper shade
---@field copper_3 string Base copper shade
---@field copper_4 string Dark copper shade
---@field copper_5 string Darkest copper shade
---@field taupe_1 string Lightest taupe shade
---@field taupe_2 string Light taupe shade
---@field taupe_3 string Base taupe shade
---@field taupe_4 string Dark taupe shade
---@field taupe_5 string Darkest taupe shade
---@field cream_1 string Lightest cream shade
---@field cream_2 string Light cream shade
---@field cream_3 string Base cream shade
---@field cream_4 string Dark cream shade
---@field cream_5 string Darkest cream shade
---@field mist_1 string Lightest mist shade
---@field mist_2 string Light mist shade
---@field mist_3 string Base mist shade
---@field mist_4 string Dark mist shade
---@field mist_5 string Darkest mist shade
---@field earth_1 string Lightest earth shade
---@field earth_2 string Light earth shade
---@field earth_3 string Base earth shade
---@field earth_4 string Dark earth shade
---@field earth_5 string Darkest earth shade
---@field shadow_1 string Lightest shadow shade
---@field shadow_2 string Light shadow shade
---@field shadow_3 string Base shadow shade
---@field shadow_4 string Dark shadow shade
---@field shadow_5 string Darkest shadow shade
---@field clay_1 string Lightest clay shade
---@field clay_2 string Light clay shade
---@field clay_3 string Base clay shade
---@field clay_4 string Dark clay shade
---@field clay_5 string Darkest clay shade
---@field stone_1 string Lightest stone shade
---@field stone_2 string Light stone shade
---@field stone_3 string Base stone shade
---@field stone_4 string Dark stone shade
---@field stone_5 string Darkest stone shade
-- === SPECIAL COLORS ===
---@field pure_white string Pure white color
---@field pure_black string Pure black color
---@field transparent string Transparent color
-- === BACKGROUND PROGRESSION ===
---@field bg_5 string Darkest background
---@field bg_4 string Dark background
---@field bg string Main background
---@field bg_2 string Light background
---@field bg_1 string Lightest background
-- === FOREGROUND PROGRESSION ===
---@field fg_darker string Darkest foreground
---@field fg string Main foreground
---@field fg_light string Light foreground
-- === PRIMARY COLORS ===
---@field primary string Primary color
---@field secondary string Secondary color
---@field accent string Accent color
-- === STATUS COLORS ===
---@field error string Error color
---@field warning string Warning color
---@field info string Info color
---@field hint string Hint color
---@field success string Success color
-- === SEMANTIC COLORS (legacy compatibility) ===
---@field purple string Purple color
---@field blue string Blue color
---@field red string Red color
---@field green string Green color
---@field orange string Orange color
---@field yellow string Yellow color
---@field cyan string Cyan color
---@field comment string Comment color
-- === EXTENDED COLORS (legacy compatibility) ===
---@field cyan2 string Dark cyan color
---@field light_gray string Light gray color
-- === GIT COLORS ===
---@field git_add string Git addition color
---@field git_change string Git change color
---@field git_delete string Git deletion color
---@field git_text string Git text color
-- === DIFF COLORS ===
---@field diff_add string Diff addition color
---@field diff_delete string Diff deletion color
---@field diff_change string Diff change color
---@field diff_text string Diff text color
-- === SELECTION AND UI COLORS ===
---@field selection string Selection background
---@field search string Search highlight color
---@field match string Matching bracket color
---@field cursor string Cursor color
---@field cursor_line string Cursor line background
---@field line_number string Line number color
---@field line_number_current string Current line number color
-- === MENU AND COMPLETION COLORS ===
---@field menu_bg string Menu background color
---@field menu_sel string Menu selection color
---@field menu_border string Menu border color
-- === FLOAT AND POPUP COLORS ===
---@field float_bg string Float window background
---@field float_border string Float window border
-- === DIAGNOSTIC COLORS ===
---@field diagnostic_error string Diagnostic error color
---@field diagnostic_warning string Diagnostic warning color
---@field diagnostic_info string Diagnostic info color
---@field diagnostic_hint string Diagnostic hint color

---@class chalk.Plugin
---@field enabled boolean Whether the plugin integration is enabled

---New 5-shade palette system
---Each color family has 5 shades: 1 (lightest) to 5 (darkest)
---@class chalk.NewPalette: table<string, string>
---@field amber_1 string Lightest amber shade (cream)
---@field amber_2 string Light amber shade
---@field amber_3 string Base amber shade
---@field amber_4 string Dark amber shade
---@field amber_5 string Darkest amber shade (amber-brown)
---@field emerald_1 string Lightest emerald shade (mint)
---@field emerald_2 string Light emerald shade
---@field emerald_3 string Base emerald shade
---@field emerald_4 string Dark emerald shade
---@field emerald_5 string Darkest emerald shade (forest)
---@field azure_1 string Lightest azure shade (sky)
---@field azure_2 string Light azure shade
---@field azure_3 string Base azure shade
---@field azure_4 string Dark azure shade
---@field azure_5 string Darkest azure shade (navy)
---@field ruby_1 string Lightest ruby shade (pink)
---@field ruby_2 string Light ruby shade
---@field ruby_3 string Base ruby shade
---@field ruby_4 string Dark ruby shade
---@field ruby_5 string Darkest ruby shade (crimson)
---@field amethyst_1 string Lightest amethyst shade (lavender)
---@field amethyst_2 string Light amethyst shade
---@field amethyst_3 string Base amethyst shade
---@field amethyst_4 string Dark amethyst shade
---@field amethyst_5 string Darkest amethyst shade (deep purple)
---@field slate_1 string Lightest slate shade (almost white)
---@field slate_2 string Light slate shade
---@field slate_3 string Base slate shade
---@field slate_4 string Dark slate shade
---@field slate_5 string Darkest slate shade (charcoal)
---@field coral_1 string Lightest coral shade (peach)
---@field coral_2 string Light coral shade
---@field coral_3 string Base coral shade
---@field coral_4 string Dark coral shade
---@field coral_5 string Darkest coral shade (rust)
---@field teal_1 string Lightest teal shade (aqua)
---@field teal_2 string Light teal shade
---@field teal_3 string Base teal shade
---@field teal_4 string Dark teal shade
---@field teal_5 string Darkest teal shade (deep teal)
---@field rose_1 string Lightest rose shade (blush)
---@field rose_2 string Light rose shade
---@field rose_3 string Base rose shade
---@field rose_4 string Dark rose shade
---@field rose_5 string Darkest rose shade (wine)
---@field sage_1 string Lightest sage shade
---@field sage_2 string Light sage shade
---@field sage_3 string Base sage shade
---@field sage_4 string Dark sage shade
---@field sage_5 string Darkest sage shade
---@field pure_white string Pure white (#ffffff)
---@field pure_black string Pure black (#000000)
---@field transparent string Transparent color (NONE)
---@field bg_lightest string Lightest background
---@field bg_2 string Light background
---@field bg_base string Base background
---@field bg_4 string Dark background
---@field bg_5 string Darkest background
---@field bg_darkest string Darkest background
---@field fg_lightest string Lightest foreground
---@field fg_lighter string Lighter foreground
---@field fg_light string Light foreground
---@field fg_base string Base foreground
---@field fg_dark string Dark foreground
---@field fg_darker string Darker foreground
---@field fg_darkest string Darkest foreground

---Semantic mapping for the new palette system
---Maps semantic roles to specific color shade combinations
---@class chalk.SemanticMappings
---@field error string Color for error states (typically ruby_3)
---@field warning string Color for warning states (typically amber_3)
---@field success string Color for success states (typically emerald_3)
---@field info string Color for info states (typically azure_3)
---@field hint string Color for hint states (typically teal_3)
---@field keyword string Color for keywords (typically amethyst_4)
---@field string string Color for strings (typically emerald_3)
---@field number string Color for numbers (typically coral_4)
---@field comment string Color for comments (typically slate_3)
---@field operator string Color for operators (typically azure_4)
---@field function_name string Color for function names (typically azure_3)
---@field variable string Color for variables (typically slate_2)
---@field constant string Color for constants (typically amber_4)
---@field cursor string Cursor color (typically azure_3)
---@field selection string Selection background (typically azure_1)
---@field search_match string Search match highlight (typically amber_2)
---@field line_number string Line number color (typically slate_3)
---@field current_line string Current line background (typically slate_1)
---@field border string Border color (typically slate_4)
---@field menu_bg string Menu background (typically slate_1)
---@field menu_selected string Menu selection (typically azure_2)
---@field git_added string Git added color (typically emerald_3)
---@field git_modified string Git modified color (typically amber_3)
---@field git_deleted string Git deleted color (typically ruby_3)
---@field git_renamed string Git renamed color (typically teal_3)
---@field diagnostic_error string Diagnostic error (typically ruby_3)
---@field diagnostic_warning string Diagnostic warning (typically amber_3)
---@field diagnostic_info string Diagnostic info (typically azure_3)
---@field diagnostic_hint string Diagnostic hint (typically slate_3)

---Complete new palette design with colors and semantic mappings
---@class chalk.NewPaletteDesign
---@field palette chalk.NewPalette The complete color palette with all shades
---@field mappings chalk.SemanticMappings Semantic role to color mappings

return M
